spring:
#  security:
#    user:
#      name: student_attendance_user
#      password: password
#      roles:
#        - USER
  application:
    name: web-service_student_attendance
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port: 8081
