spring:
  application:
    name: web-service_student_attendance
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port: 8081
